# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='\u8f93\u5165\u6587\u7ae0\u6458\u8981', max_length=40),
        ),
    ]
